# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_test_struct', [dirname(__file__)])
        except ImportError:
            import _test_struct
            return _test_struct
        if fp is not None:
            try:
                _mod = imp.load_module('_test_struct', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _test_struct = swig_import_helper()
    del swig_import_helper
else:
    import _test_struct
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class simple_struct_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, simple_struct_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, simple_struct_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["int_var"] = _test_struct.simple_struct_t_int_var_set
    __swig_getmethods__["int_var"] = _test_struct.simple_struct_t_int_var_get
    if _newclass:
        int_var = _swig_property(_test_struct.simple_struct_t_int_var_get, _test_struct.simple_struct_t_int_var_set)
    __swig_setmethods__["long_var"] = _test_struct.simple_struct_t_long_var_set
    __swig_getmethods__["long_var"] = _test_struct.simple_struct_t_long_var_get
    if _newclass:
        long_var = _swig_property(_test_struct.simple_struct_t_long_var_get, _test_struct.simple_struct_t_long_var_set)
    __swig_setmethods__["float_var"] = _test_struct.simple_struct_t_float_var_set
    __swig_getmethods__["float_var"] = _test_struct.simple_struct_t_float_var_get
    if _newclass:
        float_var = _swig_property(_test_struct.simple_struct_t_float_var_get, _test_struct.simple_struct_t_float_var_set)

    def __init__(self):
        this = _test_struct.new_simple_struct_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _test_struct.delete_simple_struct_t
    __del__ = lambda self: None
simple_struct_t_swigregister = _test_struct.simple_struct_t_swigregister
simple_struct_t_swigregister(simple_struct_t)

class tlv_base_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, tlv_base_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, tlv_base_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["type"] = _test_struct.tlv_base_t_type_set
    __swig_getmethods__["type"] = _test_struct.tlv_base_t_type_get
    if _newclass:
        type = _swig_property(_test_struct.tlv_base_t_type_get, _test_struct.tlv_base_t_type_set)
    __swig_setmethods__["length"] = _test_struct.tlv_base_t_length_set
    __swig_getmethods__["length"] = _test_struct.tlv_base_t_length_get
    if _newclass:
        length = _swig_property(_test_struct.tlv_base_t_length_get, _test_struct.tlv_base_t_length_set)
    __swig_getmethods__["value"] = _test_struct.tlv_base_t_value_get
    if _newclass:
        value = _swig_property(_test_struct.tlv_base_t_value_get)

    def __init__(self):
        this = _test_struct.new_tlv_base_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _test_struct.delete_tlv_base_t
    __del__ = lambda self: None
tlv_base_t_swigregister = _test_struct.tlv_base_t_swigregister
tlv_base_t_swigregister(tlv_base_t)

class tlv_type1_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, tlv_type1_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, tlv_type1_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["base"] = _test_struct.tlv_type1_t_base_set
    __swig_getmethods__["base"] = _test_struct.tlv_type1_t_base_get
    if _newclass:
        base = _swig_property(_test_struct.tlv_type1_t_base_get, _test_struct.tlv_type1_t_base_set)
    __swig_setmethods__["stat"] = _test_struct.tlv_type1_t_stat_set
    __swig_getmethods__["stat"] = _test_struct.tlv_type1_t_stat_get
    if _newclass:
        stat = _swig_property(_test_struct.tlv_type1_t_stat_get, _test_struct.tlv_type1_t_stat_set)
    __swig_setmethods__["info"] = _test_struct.tlv_type1_t_info_set
    __swig_getmethods__["info"] = _test_struct.tlv_type1_t_info_get
    if _newclass:
        info = _swig_property(_test_struct.tlv_type1_t_info_get, _test_struct.tlv_type1_t_info_set)
    __swig_setmethods__["something"] = _test_struct.tlv_type1_t_something_set
    __swig_getmethods__["something"] = _test_struct.tlv_type1_t_something_get
    if _newclass:
        something = _swig_property(_test_struct.tlv_type1_t_something_get, _test_struct.tlv_type1_t_something_set)

    def __init__(self):
        this = _test_struct.new_tlv_type1_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _test_struct.delete_tlv_type1_t
    __del__ = lambda self: None
tlv_type1_t_swigregister = _test_struct.tlv_type1_t_swigregister
tlv_type1_t_swigregister(tlv_type1_t)

class complex_struct_t(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, complex_struct_t, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, complex_struct_t, name)
    __repr__ = _swig_repr
    __swig_setmethods__["string"] = _test_struct.complex_struct_t_string_set
    __swig_getmethods__["string"] = _test_struct.complex_struct_t_string_get
    if _newclass:
        string = _swig_property(_test_struct.complex_struct_t_string_get, _test_struct.complex_struct_t_string_set)
    __swig_setmethods__["bytes"] = _test_struct.complex_struct_t_bytes_set
    __swig_getmethods__["bytes"] = _test_struct.complex_struct_t_bytes_get
    if _newclass:
        bytes = _swig_property(_test_struct.complex_struct_t_bytes_get, _test_struct.complex_struct_t_bytes_set)
    __swig_setmethods__["embedded"] = _test_struct.complex_struct_t_embedded_set
    __swig_getmethods__["embedded"] = _test_struct.complex_struct_t_embedded_get
    if _newclass:
        embedded = _swig_property(_test_struct.complex_struct_t_embedded_get, _test_struct.complex_struct_t_embedded_set)
    __swig_setmethods__["pointer_array_count"] = _test_struct.complex_struct_t_pointer_array_count_set
    __swig_getmethods__["pointer_array_count"] = _test_struct.complex_struct_t_pointer_array_count_get
    if _newclass:
        pointer_array_count = _swig_property(_test_struct.complex_struct_t_pointer_array_count_get, _test_struct.complex_struct_t_pointer_array_count_set)
    __swig_setmethods__["pointer_array"] = _test_struct.complex_struct_t_pointer_array_set
    __swig_getmethods__["pointer_array"] = _test_struct.complex_struct_t_pointer_array_get
    if _newclass:
        pointer_array = _swig_property(_test_struct.complex_struct_t_pointer_array_get, _test_struct.complex_struct_t_pointer_array_set)
    __swig_setmethods__["tlv"] = _test_struct.complex_struct_t_tlv_set
    __swig_getmethods__["tlv"] = _test_struct.complex_struct_t_tlv_get
    if _newclass:
        tlv = _swig_property(_test_struct.complex_struct_t_tlv_get, _test_struct.complex_struct_t_tlv_set)

    def __init__(self):
        this = _test_struct.new_complex_struct_t()
        try:
            self.this.append(this)
        except Exception:
            self.this = this
    __swig_destroy__ = _test_struct.delete_complex_struct_t
    __del__ = lambda self: None
complex_struct_t_swigregister = _test_struct.complex_struct_t_swigregister
complex_struct_t_swigregister(complex_struct_t)


def alloc_complex_struct(array_count):
    return _test_struct.alloc_complex_struct(array_count)
alloc_complex_struct = _test_struct.alloc_complex_struct

def free_complex_struct(cs):
    return _test_struct.free_complex_struct(cs)
free_complex_struct = _test_struct.free_complex_struct

def print_complex_struct(cs):
    return _test_struct.print_complex_struct(cs)
print_complex_struct = _test_struct.print_complex_struct
# This file is compatible with both classic and new-style classes.


